# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=32)),
                ('bread', models.CharField(max_length=32)),
                ('quantity', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
