# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20171009_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='bread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Bread'),
        ),
    ]
