# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20171009_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Bread')),
            ],
        ),
    ]
